--1

--without set operator

SELECT DISTINCT ACT_FIRSTNAME, ACT_LASTNAME
FROM ACTOR
WHERE (ACT_FIRSTNAME || ' ' || ACT_LASTNAME) IN (
    SELECT DIR_FIRSTNAME || ' ' || DIR_LASTNAME
    FROM DIRECTOR
);

--with set operator

SELECT NAME
FROM (
    SELECT ACT_FIRSTNAME || ' ' || ACT_LASTNAME AS NAME
    FROM ACTOR
    UNION ALL
    SELECT DIR_FIRSTNAME || ' ' || DIR_LASTNAME AS NAME
    FROM DIRECTOR
)
GROUP BY NAME
HAVING COUNT(*) > 1;

--2
SELECT ACT_FIRSTNAME, COUNT(*) AS NUM_ACTRESSES
FROM ACTOR
WHERE ACT_GENDER = 'F'
GROUP BY ACT_FIRSTNAME
HAVING COUNT(*) > 1;

--3
SELECT ACT_FIRSTNAME || ' ' || ACT_LASTNAME AS FULL_NAME
FROM ACTOR
UNION
SELECT DIR_FIRSTNAME || ' ' || DIR_LASTNAME AS FULL_NAME
FROM DIRECTOR;

--4
SELECT MOV_TITLE
FROM MOVIE
WHERE MOV_ID NOT IN (
    SELECT DISTINCT MOV_ID
    FROM RATING
);


--5
SELECT AVG(REV_STARS)
FROM RATING;


--6
SELECT MOV_ID, MIN(REV_STARS) AS MIN_RATING
FROM RATING
GROUP BY MOV_ID
ORDER BY MIN_RATING DESC;

--7

SELECT MOV_TITLE
FROM MOVIE
WHERE MOV_ID IN (
SELECT MOV_ID
FROM RATING
GROUP BY MOV_ID
HAVING AVG(REV_STARS) > (SELECT AVG(REV_STARS) FROM RATING));


--8

SELECT a.ACT_FIRSTNAME || ' ' || a.ACT_LASTNAME AS ACTOR_ACTRESS_NAME,
m.MOV_TITLE,
COUNT(r.MOV_ID) AS NUMBER_OF_RATINGS
FROM ACTOR a, CASTS c, MOVIE m, RATING r
WHERE a.ACT_ID = c.ACT_ID
AND c.MOV_ID = m.MOV_ID
AND m.MOV_ID = r.MOV_ID
GROUP BY a.ACT_FIRSTNAME, a.ACT_LASTNAME, m.MOV_TITLE
ORDER BY ACTOR_ACTRESS_NAME, NUMBER_OF_RATINGS DESC;


--9
SELECT d.DIR_FIRSTNAME || ' ' || d.DIR_LASTNAME AS Director_Name
FROM DIRECTOR d
JOIN DIRECTION di ON d.DIR_ID = di.DIR_ID
JOIN (
SELECT MOV_ID, AVG(REV_STARS) AS Avg_Rev_Star
FROM RATING
GROUP BY MOV_ID
HAVING AVG(REV_STARS) = (
SELECT MAX(Avg_Rev_Star)
FROM (
SELECT MOV_ID, AVG(REV_STARS) AS Avg_Rev_Star
FROM RATING
GROUP BY MOV_ID))) 
r ON di.MOV_ID = r.MOV_ID;


--10
SELECT m.MOV_ID, m.MOV_TITLE, m.MOV_YEAR, m.MOV_TIME, m.MOV_LANGUAGE, m.MOV_RELEASEDATE, m.MOV_COUNTRY
FROM MOVIE m, CASTS c, DIRECTION d
WHERE m.MOV_ID = c.MOV_ID
AND m.MOV_ID = d.MOV_ID
AND c.ACT_ID = d.DIR_ID;


--11
SELECT m.MOV_TITLE, AVG(r.REV_STARS) AS AVERAGE_RATING
FROM MOVIE m, RATING r
WHERE m.MOV_ID = r.MOV_ID
GROUP BY m.MOV_TITLE
HAVING AVG(r.REV_STARS) > 7
ORDER BY AVERAGE_RATING DESC;


--12
SELECT r.REV_NAME, COUNT(*) AS Lowest_Rev_Star_Count
FROM REVIEWER r, RATING ra
WHERE r.REV_ID = ra.REV_ID
AND ra.REV_STARS = (
SELECT MIN(REV_STARS)
FROM RATING)
GROUP BY r.REV_NAME
HAVING COUNT(*) = (
SELECT MAX(Count_Rev_Star)
FROM (
SELECT COUNT(*) AS Count_Rev_Star
FROM REVIEWER r, RATING ra
WHERE r.REV_ID = ra.REV_ID
AND ra.REV_STARS = (
SELECT MIN(REV_STARS)
FROM RATING)
GROUP BY r.REV_NAME));


--13
SELECT (a.ACT_FIRSTNAME || ' ' || a.ACT_LASTNAME) AS Actor_Actress_Name, AVG(m.MOV_TIME) AS Average_Runtime
FROM ACTOR a, CASTS c, MOVIE m
WHERE a.ACT_ID = c.ACT_ID
AND c.MOV_ID = m.MOV_ID
AND a.ACT_ID NOT IN (
SELECT DISTINCT c.ACT_ID
FROM CASTS c, DIRECTION d, DIRECTOR di
WHERE c.MOV_ID = d.MOV_ID
AND d.DIR_ID = di.DIR_ID
AND (di.DIR_FIRSTNAME || ' ' || di.DIR_LASTNAME) = 'James Cameron')
GROUP BY a.ACT_FIRSTNAME, a.ACT_LASTNAME;






